### ISSUE TITLE
Action Bar Bug

### ISSUE THREAD

**Issue by breezefps** [PedroJM96/CoreLibBukkit#1] opened 2023-06-11 11:10 UTC
![image](https://github.com/PedroJM96/CoreLibBukkit/assets/51733120/63e4cc8a-e5b0-44e0-86bf-88e9e0696a23)

Reporting the bug.

**Comment by Tian-MC** [comment] 2023-06-13 09:06
I have the same errors, it's not a bug, it's a missing library

**Comment by GodDirtman** [comment] 2023-06-17 18:31
Same here.

**Comment by PedroJM96** [comment] 2023-07-21 20:14
Fixed in the latest version

**Closed by PedroJM96** 2023-07-21 20:14 UTC
